FROM python:3.11.8-slim-bookworm

COPY ./requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt && \
    rm /tmp/requirements.txt

RUN mkdir -p /usr/src/trainer
COPY ./ /usr/src/trainer

WORKDIR /usr/src/
